name: lake_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.0"
  shared_preferences: "^0.4.1"
  firebase_database: "^0.4.6"
  flutter_secure_storage: "^3.0.0"
  firebase_auth: "^0.5.7"
  qr_flutter: "^1.1.1"
  pub_mediator: "^1.0.1"
  camera: "^0.1.2"
  path_provider: "^0.4.0"
  image_picker: "^0.4.0"
  image: "^1.1.30"
  secure_string: "^2.0.0"
  firebase_messaging: "^0.2.5"
  firebase_storage: "^0.3.3"
  barcode_scan: "^0.0.4"
  url_launcher: "^3.0.1"
  firebase_analytics: "^0.3.3"
  #flutter_local_notifications: "^0.1.0"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/png/01d.png
    - assets/png/01n.png
    - assets/png/02d.png
    - assets/png/02n.png
    - assets/png/03d.png
    - assets/png/09d.png
    - assets/png/10d.png
    - assets/png/10n.png
    - assets/png/11d.png
    - assets/png/13d.png
    - assets/png/50d.png
    - assets/png/nouser.png

  fonts:
    - family: Roboto
      fonts:
       - asset: assets/fonts/Roboto/Roboto-Regular.ttf
       - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    - family: Raleway
      fonts:
       - asset: assets/fonts/Raleway/Raleway-Regular.ttf
       - asset: assets/fonts/Raleway/Raleway-Thin.ttf
       - asset: assets/fonts/Raleway/Raleway-Bold.ttf
    - family: Alert
      fonts:
      - asset: assets/fonts/Raleway/Raleway-Bold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
